name: build-pkg
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Build package
        run: |
          pipenv install
          sh build_pkg.sh
          pipenv run pip install --upgrade build

      - name: Run getting_started.py
        run: pipenv run python getting_started.py 
