name: BUILD-PKG

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Build package
          sh build_pkg.sh
      - name: Build package
          pipenv run python getting_started.py 