name: build-pkg
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Build package
        run: sh build_pkg.sh
      - name: Build package
        run: pipenv run python getting_started.py 